config/routes.rb
McaDraws::Application.routes.draw do
  get "draws/index"

  get "draws/show"

  resources :bonspiels do 
    member do
      get 'load'
    end
    resources :draws, :only => [:show, :index]
  end

  root :to => 'bonspiels#index'

end

app/models/bonspiel.rb
require 'open-uri'

class Bonspiel < ActiveRecord::Base
  attr_accessible :name
  
  has_many :draws, :order => 'number desc'
  has_many :events
  
  
  def load_draws
    root_url = "http://www.curlmanitoba.org/"
    doc = Nokogiri::HTML(open(root_url + 'mca-mens-bonspiel'))
    draw_links = doc.css('p a').select{|link| link['href'].include?('/DRAW') || link['href'].include?('/PARTIAL-DRAW') }
    parsed = DrawParser.all.map(&:filename)
    draw_links.reject!{|link| parsed.include?(link['href']) }
    draw_links.each do |link|

      match = /DRAW(\d*)/.match(link['href'])
      d = Draw.new(:number => match[1].to_i, :partial => link['href'].include?('PARTIAL'))
      io     = open(root_url + link['href'])
      reader = PDF::Reader.new(io)

      event = nil
      reader.pages.each do |page|
        found = false
        page.text.split("\n").each do |line|
          if line =~ /^      (.*?)/
            line = 'ASHAM' if line.include?('ASHAM FINALISTS')
            event = Event.where(:name => line.strip).first
            event = Event.create(:name => line.strip) if event.nil?
          end
          found = true if line.include?('SHEET')
          if found && line.length >= 82
            m       = Match.new
            m.event = event
            m.black = Rink.where(:name => line[6..36].strip).first || Rink.new(:name => line[6..36].strip, :club => line[37..52].strip)
            m.red   = Rink.where(:name => line[52..82].strip).first || Rink.new(:name => line[52..82].strip, :club => line[83..-1].strip)
            m.sheet = line[0..5].strip
            d.matches << m
          end
        end
      end
      self.draws << d
      DrawParser.create(:filename => link['href'])
    end
    self.save!
    
    draw_links
  end
end

app/models/bonspiel_sweeper.rb
class BonspielSweeper < ActionController::Caching::Sweeper
  observe Bonspiel # This sweeper is going to keep an eye on the Product model
 
  # If our sweeper detects that a Product was created call this
  def after_create(product)
    expire_cache_for(product)
  end
 
  # If our sweeper detects that a Product was updated call this
  def after_update(product)
    expire_cache_for(product)
  end
 
  # If our sweeper detects that a Product was deleted call this
  def after_destroy(product)
    expire_cache_for(product)
  end
 
  private
  def expire_cache_for(product)
    # Expire the index page now that we added a new product
    expire_page(:controller => 'bonspeils', :action => 'show')
 
  end
end

app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :bottom_sheet, :name, :top_sheet
  
  def self.find_for_sheet(sheet)
    club_data = [[(1..9), "Granite"],
    [(41..48), "Heather"],
    [(51..56), "Fort Rouge"],
    [(71..75), "Elmwood"],
    [(91..96), "Deer Lodge"],
    [(101..106), "Pembina"],
    [(111..116), "Fort Garry"],
    [(121..125), "Victoria"],
    [(131..136), "St. Vital"],
    [(141..145), "West Kildonan"],
    [(161..165), "Thistle"],
    [(201..206), "Rossmere"],
    [(211..215), "Charleswood"],
    [(221..226), "Wildewood"],
    [(231..238), "Assiniboine Memorial"],
    [(241..244), "West St. Paul"],
    [(261..266), "East St Paul"],
    [(271..274), "Springfield"],
    [(281..283), "Stony Mountain"],
    [(301..303), "La Salle"],
    [(311..316), "Selkirk"],
    [(351..353), "St.Adolphe"]]
    
    club = club_data.select {|c| c[0].include?(sheet.to_i) }.first
    Club.new(:name => club[1]) if club
  end
  
end

app/models/draw.rb
class Draw < ActiveRecord::Base
  attr_accessible :number, :partial
  
  has_many :matches
end

app/models/draw_parser.rb
class DrawParser < ActiveRecord::Base
  attr_accessible :filename
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :bonspiel_id, :name
  
  belongs_to :bonspiel
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :black, :red, :sheet, :black_score, :red_score
  
  belongs_to :black, :class_name => "Rink", :foreign_key => "black_id"
  belongs_to :red, :class_name => "Rink", :foreign_key => "red_id"
  belongs_to :event
  
  def club
    c = Club.find_for_sheet(sheet)
    c.nil? ? 'Unknown' : c.name
  end
  
  def winner
    return unless complete?
    black_score.to_i > red_score.to_i ? black : red
  end
  
  def complete?
    !black_score.nil? && !red_score.nil?
  end
end

app/models/rink.rb
class Rink < ActiveRecord::Base
  attr_accessible :name, :club
  
  # belongs_to :club
  has_many :matches, :class_name => 'Match', :finder_sql => proc {['SELECT matches.* FROM matches WHERE black_id = :id OR red_id = :id', {id: id}]}
  
  def to_s
    "#{name} (#{club})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bonspiels_controller.rb
class BonspielsController < ApplicationController
  
  caches_page :show
  caches_page :all
  
  def index    
    rinks = Rink.limit(32).order('RAND()').all
    @bracket = BracketFactory.new(rinks)
    @rounds = JSON.generate(@bracket.simulate)
  end
  
  def show
    @bonspiel = Bonspiel.find(params[:id])
    @draws = @bonspiel.draws.order('number desc').limit(4)
  end

  def all
    @bonspiel = Bonspiel.find(params[:id])
    @draws = @bonspiel.draws.order('number desc')
    render :action => :show
  end
  
  def load
    require 'open-uri'
    b = Bonspiel.find(params[:id])
    root_url = "http://www.curlmanitoba.org/"
    doc = Nokogiri::HTML(open(root_url + 'mca-mens-bonspiel'))
    draw_links = doc.css('p a').select{|link| link['href'].include?('/DRAW') || link['href'].include?('/PARTIAL-DRAW') }
    parsed = DrawParser.all.map(&:filename)
    draw_links.reject!{|link| parsed.include?(link['href']) }
    draw_links.each_with_index do |link, i|

      puts "Parsing #{link['href']}"
      match = /DRAW(\d*)/.match(link['href'])
      d = Draw.new(:number => match[1].to_i, :partial => link['href'].include?('PARTIAL'))
      io     = open(root_url + link['href'])
      reader = PDF::Reader.new(io)

      event = nil
      reader.pages.each do |page|
        found = false
        page.text.split("\n").each do |line|
          if line =~ /^      (.*?)/
            line = 'ASHAM' if line.include?('ASHAM FINALISTS')
            event = Event.where(:name => line.strip).first
            event = Event.create(:name => line.strip) if event.nil?

          end
          found = true if line.include?('SHEET')
          if found && line.length >= 82
            m       = Match.new
            m.event = event
            m.black = Rink.where(:name => line[6..36].strip).first || Rink.new(:name => line[6..36].strip, :club => line[37..52].strip)
            m.red   = Rink.where(:name => line[52..82].strip).first || Rink.new(:name => line[52..82].strip, :club => line[83..-1].strip)
            m.sheet = line[0..5].strip
            d.matches << m
          end
        end
      end
      b.draws << d
      DrawParser.create(:filename => link['href'])
    end
    
    b.save!
    `rm -Rf #{Rails.root}/public/bonspiels`
    
    render :text => "Load attempted: #{draw_links.map{|l| l['href']}.inspect}"
  end

  def next_power_of_two(n)
    return n if (n-1)&n == 0
    pow=1
    while (n >= 0x100000000) do  pow += 32; n >>= 32; end
    if (n & 0xFFFF0000 > 0) then pow += 16; n >>= 16; end
    if (n & 0xFF00 > 0)     then pow += 8;  n >>= 8;  end
    if (n & 0xF0 > 0)       then pow += 4;  n >>= 4; end
    if (n & 0xC > 0)        then pow += 2;  n >>= 2; end
    if (n & 0x2 > 0)        then pow += 1;  n >>= 1; end
    1<<pow
  end
  
  def seed_order(size)
    bracket_list = []
    0.upto(size-1) do |i|
      bracket_list << i
    end

    slice = 1
    while slice < bracket_list.length/2
      temp = bracket_list
      bracket_list = []

      while temp.length > 0
        bracket_list.concat temp.slice!(0, slice)       # n from the beginning
        bracket_list.concat temp.slice!(-slice, slice)  # n from the end
      end

      slice *= 2
    end

    bracket_list
  end  

end

app/controllers/draws_controller.rb
class DrawsController < ApplicationController
  before_filter :find_bonspiel

  def index
    @draws = @bonspiel.draws
  end

  def show
    @draw = @bonspiel.draws.find(params[:id])
  end
  
  protected
  
  def find_bonspiel
    @bonspiel = Bonspiel.find(params[:bonspiel_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonspiels_helper.rb
module BonspielsHelper
end

app/helpers/draws_helper.rb
module DrawsHelper
end

app/views/bonspiels/index.html.erb
<div class="g_gracket" data-gracket="<%= @rounds%>"></div>

app/views/bonspiels/show.html.erb
<h1><%=@bonspiel.name%></h1>

<p>
  <strong>Select a team:</strong>
  <%= select_tag('rink', options_from_collection_for_select(Rink.order('name ASC').all, :name, :name), :id => 'rink_select') %>
</p>

<% @draws.each do |draw| %>
  
  <h2>Draw <%= draw.number %> <%= "(Partial)" if draw.partial? %></h2>

  <table class="table table-striped">
    <% if draw.partial? %>
      <caption><strong>NOTE this is a partial draw listing - Teams playing back to back will not be shown, the winners will stay in the club they played in.</strong></caption>
    <% end %>
    <thead>
      <th>Event</th>
      <th>Sheet</th>
      <th>Club</th>
      <th>Black</th>
      <th>Score</th>
      <th>Red</th>
      <th>Score</th>
    </thead>
    <tbody>
      <% draw.matches.each do |m| %>
        <tr>
          <td><%= m.event.try(:name) %></td>
          <td><%= m.sheet %></td>
          <td><%= m.club %></td>
          <td class="<%=(m.black == m.winner ? "winner" : "")%>"><%= m.black %></td>
          <td class="<%=(m.black == m.winner ? "winner" : "")%>"><%= m.black_score %></td>
          <td class="<%=(m.black == m.winner ? "winner" : "")%>"><%= m.red %></td>
          <td class="<%=(m.black == m.winner ? "winner" : "")%>"><%= m.red_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/draws/_draw.html.haml
%section{:id => "draw_#{draw.number}"}
  %h2
    ="Draw #{draw.number}"
    = "(Partial)" if draw.partial?
  %table.table.table-striped
    - if draw.partial?
      %caption 
        %strong NOTE this is a partial draw listing - Teams playing back to back will not be shown, the winners will stay in the club they played in.
    %thead
      %tr
        %th Event
        %th Sheet
        %th Club
        %th Black
        %th Score
        %th Red
        %th Score
    %tbody
      - draw.matches.each do |m|
        %tr
          %td= m.event.try(:name)
          %td= m.sheet
          %td= m.club
          %td{:class => (m.black == m.winner ? "winner" : "")}
            = m.black
          %td{:class => m.black == m.winner ? "winner" : ""}
            = m.black_score
          %td{:class => m.red == m.winner ? "winner" : ""}
            = m.red
          %td{:class => m.red == m.winner ? "winner" : ""}
            = m.red_score

app/views/draws/index.html.haml
- content_for :sidebar do
  #drawbar
    %ul.nav.nav-list.bs-docs-sidenav.affix-top
      - @draws.each do |d|
        %li
          = link_to("Draw #{d.number}", %Q{#draw_#{d.number}})

%h1=@bonspiel.name

%p
  = link_to('Back to Bonspiel', bonspiel_path(@bonspiel))

%p
  %strong Select a team: 
  = select_tag('rink', options_from_collection_for_select(Rink.order('name ASC').all, :name, :name), :id => 'rink_select')

= render :partial => 'draws/draw', :collection => @draws

app/views/draws/show.html.haml
%h1=@bonspiel.name

%p
  = link_to('Back to Bonspiel', bonspiel_path(@bonspiel))
  

= render :partial => 'draw', :object => @draw

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MCA Draw Viewer</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:head) %>
    <%= csrf_meta_tag %>
    <%= yield :js %>
    
  </head>
  <body>
    <div class='navbar'>
      <div class='navbar-inner'>
        <div class='container'>
          <a class='brand' href='/'>MCA Draw Viewer</a>
        </div>
      </div>
    </div>
    <div class='container-fluid'>
      <div class='content'>
        <%= yield %>
      </div>
    </div>
    <div id='dialog_container'>
      <%= yield :dialogs %>
    </div>
  </body>
</html>